"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 21:14:54.249770
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('norm_key', sa.String(length=200), nullable=False),
    sa.Column('street_number', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('display_address', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geocode_source', sa.String(length=32), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('norm_key')
    )
    op.create_table('merge_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('undone_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_blobs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('sha256')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('disabled_reason', sa.Text(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('expected_min', sa.Integer(), nullable=False),
    sa.Column('expected_max', sa.Integer(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('last_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('norm_name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_norm_name'), ['norm_name'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('done', sa.Integer(), nullable=False),
    sa.Column('step', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('norm_unit', sa.String(length=40), nullable=False),
    sa.Column('unit_label', sa.String(length=80), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'norm_unit')
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_building_id'), ['building_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('merged_into_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['merged_into_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_events_job_id'), ['job_id'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('listings_found', sa.Integer(), nullable=True),
    sa.Column('healthy', sa.Boolean(), nullable=True),
    sa.Column('health_notes', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_source_id'), ['source_id'], unique=False)

    op.create_table('source_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('last_verified', sa.DateTime(), nullable=False),
    sa.Column('consecutive_misses', sa.Integer(), nullable=False),
    sa.Column('latest_snapshot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['latest_snapshot_id'], ['listing_snapshots.id'], name='fk_sl_latest_snapshot', use_alter=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id')
    )
    with op.batch_alter_table('source_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_listings_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_listings_unit_id'), ['unit_id'], unique=False)

    op.create_table('unit_prefs',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('unit_tags',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('unit_id', 'tag')
    )
    op.create_table('contact_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('norm', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'norm')
    )
    with op.batch_alter_table('contact_names', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_names_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_names_norm'), ['norm'], unique=False)

    op.create_table('contact_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'value')
    )
    with op.batch_alter_table('contact_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_points_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_points_contact_id'), ['contact_id'], unique=False)

    op.create_table('outreach_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('follow_up_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_log_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outreach_log_contact_id'), ['contact_id'], unique=False)

    op.create_table('raw_fetches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('blob_sha256', sa.String(length=64), nullable=True),
    sa.Column('via', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['blob_sha256'], ['raw_blobs.sha256'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_fetches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_fetches_scrape_run_id'), ['scrape_run_id'], unique=False)

    op.create_table('status_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_listing_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=True),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.ForeignKeyConstraint(['source_listing_id'], ['source_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_events_source_listing_id'), ['source_listing_id'], unique=False)

    op.create_table('listing_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_listing_id', sa.Integer(), nullable=False),
    sa.Column('scrape_run_id', sa.Integer(), nullable=True),
    sa.Column('raw_fetch_id', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('address_raw', sa.Text(), nullable=True),
    sa.Column('unit_raw', sa.String(length=80), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Float(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('avail_structured_raw', sa.Text(), nullable=True),
    sa.Column('avail_structured_date', sa.Date(), nullable=True),
    sa.Column('avail_text_raw', sa.Text(), nullable=True),
    sa.Column('avail_text_date', sa.Date(), nullable=True),
    sa.Column('avail_text_kind', sa.String(length=16), nullable=True),
    sa.Column('avail_text_confidence', sa.Float(), nullable=True),
    sa.Column('avail_text_method', sa.String(length=16), nullable=True),
    sa.Column('pets', sa.Text(), nullable=True),
    sa.Column('parking', sa.Text(), nullable=True),
    sa.Column('utilities', sa.Text(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_raw', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['raw_fetch_id'], ['raw_fetches.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.ForeignKeyConstraint(['source_listing_id'], ['source_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_snapshots_scrape_run_id'), ['scrape_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_snapshots_source_listing_id'), ['source_listing_id'], unique=False)
        batch_op.create_index('ix_snap_listing_observed', ['source_listing_id', 'observed_at'], unique=False)

    op.create_table('contact_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name_raw', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('review_state', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['listing_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_mentions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_mentions_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_mentions_snapshot_id'), ['snapshot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_mentions_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_contact_mentions_contact_id'))
        batch_op.drop_index(batch_op.f('ix_contact_mentions_company_id'))

    op.drop_table('contact_mentions')
    with op.batch_alter_table('listing_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snap_listing_observed')
        batch_op.drop_index(batch_op.f('ix_listing_snapshots_source_listing_id'))
        batch_op.drop_index(batch_op.f('ix_listing_snapshots_scrape_run_id'))

    op.drop_table('listing_snapshots')
    with op.batch_alter_table('status_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_events_source_listing_id'))

    op.drop_table('status_events')
    with op.batch_alter_table('raw_fetches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_fetches_scrape_run_id'))

    op.drop_table('raw_fetches')
    with op.batch_alter_table('outreach_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_log_contact_id'))
        batch_op.drop_index(batch_op.f('ix_outreach_log_company_id'))

    op.drop_table('outreach_log')
    with op.batch_alter_table('contact_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_points_contact_id'))
        batch_op.drop_index(batch_op.f('ix_contact_points_company_id'))

    op.drop_table('contact_points')
    with op.batch_alter_table('contact_names', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_names_norm'))
        batch_op.drop_index(batch_op.f('ix_contact_names_contact_id'))

    op.drop_table('contact_names')
    op.drop_table('unit_tags')
    op.drop_table('unit_prefs')
    with op.batch_alter_table('source_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_listings_unit_id'))
        batch_op.drop_index(batch_op.f('ix_source_listings_source_id'))

    op.drop_table('source_listings')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_source_id'))

    op.drop_table('scrape_runs')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_events_job_id'))

    op.drop_table('job_events')
    op.drop_table('contacts')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_building_id'))

    op.drop_table('units')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_norm_name'))

    op.drop_table('companies')
    op.drop_table('sources')
    op.drop_table('settings')
    op.drop_table('raw_blobs')
    op.drop_table('merge_log')
    op.drop_table('buildings')
    # ### end Alembic commands ###
