"""listing link lock, mention listing

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 22:18:39.127768
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_mentions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_listing_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suggested_contact_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_contact_mentions_source_listing_id'), ['source_listing_id'], unique=False)
        batch_op.create_foreign_key('fk_mention_source_listing', 'source_listings', ['source_listing_id'], ['id'])
        batch_op.create_foreign_key('fk_mention_suggested_contact', 'contacts', ['suggested_contact_id'], ['id'])

    with op.batch_alter_table('source_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_locked', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_listings', schema=None) as batch_op:
        batch_op.drop_column('link_locked')

    with op.batch_alter_table('contact_mentions', schema=None) as batch_op:
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_mention_suggested_contact', type_='foreignkey')
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('fk_mention_source_listing', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contact_mentions_source_listing_id'))
        batch_op.drop_column('suggested_contact_id')
        batch_op.drop_column('source_listing_id')

    # ### end Alembic commands ###
