"""owners, leads, contact kind

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 02:28:23.944584
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('manager_company_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['manager_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_id', 'company_id', 'source')
    )
    with op.batch_alter_table('building_owners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_building_owners_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_building_owners_company_id'), ['company_id'], unique=False)

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=16), nullable=True))

    with op.batch_alter_table('source_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_override', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('triage', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_listings', schema=None) as batch_op:
        batch_op.drop_column('triage')
        batch_op.drop_column('address_override')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('kind')

    with op.batch_alter_table('building_owners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_building_owners_company_id'))
        batch_op.drop_index(batch_op.f('ix_building_owners_building_id'))

    op.drop_table('building_owners')
    # ### end Alembic commands ###
